-- 002_stations.up.sql
--
-- The stations table is the cloud's view of each install. The
-- station_id is generated locally by the install (spec §6.1
-- "FM-10482") and sent in the first heartbeat, so we never
-- generate it server-side. The api_key_hash is a SHA-256 of the
-- per-station API key the install generated — we never store the
-- raw key.
--
-- status: active (default) / inactive (owner paused) / suspended
--         (you revoked access). The sync agent checks this on
--         every heartbeat and 403s on suspended.

CREATE TABLE stations (
    station_id        TEXT PRIMARY KEY,            -- 'FM-XXXXX', generated by install
    owner_org_id      UUID REFERENCES organizations(id),
    install_date      TIMESTAMP NOT NULL,
    hardware_tier     TEXT NOT NULL,               -- basic/standard/enhanced/pro
    software_version  TEXT NOT NULL,
    api_key_hash      TEXT NOT NULL,               -- sha256(api_key), hex
    last_heartbeat_at TIMESTAMP,
    status            TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive', 'suspended'))
);

CREATE INDEX idx_stations_org ON stations (owner_org_id);
CREATE INDEX idx_stations_last_hb ON stations (last_heartbeat_at);